Adding checks for existing binaries
Signed-off-by: Vagelis Prokopiou <vagelis.prokopiou@gmail.com>

diff --git a/bin/git-patch-apply-from-url b/bin/git-patch-apply-from-url
--- a/bin/git-patch-apply-from-url
+++ b/bin/git-patch-apply-from-url
@@ -1,5 +1,8 @@
 #!/usr/bin/env bash
 
+command -v curl > /dev/null 2>&1 || { echo "curl is required but it's not installed."; exit 1; }
+command -v git > /dev/null 2>&1 || { echo "git is required but it's not installed."; exit 1; }
+
 if [[ -n "$1" ]]; then
     curl "${1}" | git apply -v;
     exit 0;    
